---
# Defaults para a role mysql

db_engine: "mysql"
db_version: "8.0"
db_port: 3306
db_bind_address: "127.0.0.1"
innodb_buffer_pool_size: "256M"
max_connections: 100

# Backup
backup_enabled: false
backup_path: "/var/backups/mysql"
backup_schedule: "0 2 * * *"

# Replicação
replication_enabled: false
server_id: 1
