---
# Handlers para a role mysql

- name: Restart mysql
  service:
    name: mysql
    state: restarted
  become: yes

- name: Reload mysql
  service:
    name: mysql
    state: reloaded
  become: yes
